### PR TITLE
a function to create professor account is added

### PR DESCRIPTION
**Pull request by eabujayyab**

### CODE REVIEW

**Review by AbinavParupudi — APPROVED** [review]
Your code is good

**Review by harneetkaur3 — APPROVED** [review]
Your code fulfilling the task... You can also add comments to your code

**Review by sanjana-dharan96 — APPROVED** [review]
Approved the implementation of Professor account. Pending: calling this in the main function

**Comment by eabujayyab** [comment]
a function to create professor account is added

**Pull request merged**
